Make a stage into a categorised list of links to slides from presentations
hyperoslo/hyper-radar pull request #2
Opened 2017-03-08 12:09 UTC by vadymmarkov

1) As suggested by @JohnSundell, instead of sharing your slides directly in this repo, it makes more sense to have a file with links to SpeakerDeck/Slideshare keynotes.
2) Use "summary" instead of "review" to make it clear that it's not an article, but more like a structured overview. The next step is to add a template.

2017-03-08 12:10 UTC, onmyway133 approved these changes

2017-03-08 13:08 UTC, sindrenm requested changes

2017-03-08 13:08 UTC, sindrenm commented on README.md
> +Use (https://github.com/hyperoslo/hyper-radar/blob/master/Library/inspiration.md)
Did you forget the link text for this one? Or did you mean to use `<` and `>` instead?

2017-03-08 13:21 UTC, vadymmarkov commented on README.md
> +Use (https://github.com/hyperoslo/hyper-radar/blob/master/Library/inspiration.md)
@sindrenm Yeah, I forgot to make it into a link. Thanks!

2017-03-09 08:39 UTC, sindrenm approved these changes

2017-03-09 09:02 UTC, merged