Feature: summary template
hyperoslo/hyper-radar pull request #3
Opened 2017-03-10 12:02 UTC by vadymmarkov

@hyperoslo/everyone 
Here we introduce a template for writing technical reviews or summaries. The idea is to copy a template and fill in the form. Using a template would make it easier to keep all the summaries similar to each other.

2017-03-10 12:13 UTC, onmyway133 commented
@vadymmarkov Should we use PR templating for this https://github.com/blog/2111-issue-and-pull-request-templates ?

2017-03-10 12:16 UTC, vadymmarkov commented
@onmyway133 PR template is for PR's description. And this template is for MD files.

2017-03-10 13:14 UTC, sindrenm requested changes
Nice template! But should we have a one-size-fits-all template, and if so, does this one fit all?

2017-03-10 13:14 UTC, sindrenm commented on README.md
> +don't be afraid to express your own views and opinions. Have you built
:tada:

2017-03-10 13:14 UTC, sindrenm commented on Lab/template.md
> +spacecraft? Then you are in the right place!
:rocket:

2017-03-10 13:14 UTC, sindrenm commented on Lab/template.md
> +Have you tried something promising? Share your experience to help in our
Should we ditch the “in” at the end here?

2017-03-10 13:14 UTC, sindrenm commented on Lab/template.md
> +completely new).
Mind if we indent this line to line up under “Choose” above?

2017-03-10 13:14 UTC, sindrenm commented on Lab/template.md
> +* License:	MIT
Shouldn't this be a space?

2017-03-10 13:59 UTC, onmyway133 commented on Lab/template.md
> +spacecraft? Then you are in the right place!
I love to see @timkurvers 's warcraft game here

2017-03-10 14:07 UTC, timkurvers commented on Lab/template.md
> +spacecraft? Then you are in the right place!
Can do! (later)

2017-03-10 15:24 UTC, vadymmarkov commented
@sindrenm I think this template is more for reviewing open source tools, frameworks, different kind of services, like for example https://flutter.io (It's a task for you btw 😛). One can potentially write an article on Medium and then make a short summary out of it to publish here under an appropriate category in `Lab`. On the other hand,  it might make more sense to leave `Lab` only for tools and create more folders, for example `Playground` for things like @timkurvers 's warcraft game, with it's own template and set of questions. What do you think @sindrenm?

2017-03-13 11:39 UTC, sindrenm commented
Yeah, that sounds reasonable, @vadymmarkov! :+1:

2017-03-13 11:39 UTC, sindrenm approved these changes

2017-03-13 12:05 UTC, merged